version: '3.7'

networks:
  ts_net:
    external:
      name: ts_net

services:
  rabbitmq:
    image: bitnami/rabbitmq:latest
    hostname: rabbitmq
    environment:
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=Welcome1#
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - .:/bitnami
    networks:
      - ts_net
  telegram:
    build: .
    container_name: telegram
    ports:
      - 9888:9888
    depends_on:
      - rabbitmq
    restart: on-failure
    volumes:
      - .:/telegram-sync:rw
    networks:
      - ts_net