version: '3.7'

networks:
  ts_net:
    external:
      name: ts_net

services:
  rabbitmq:
    image: bitnami/rabbitmq:latest
    hostname: rabbitmq
    environment:
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=Welcome1#
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - .:/bitnami
    networks:
      - ts_net
  telegram:
    build: .
    container_name: telegram
    environment:
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=Welcome1#
      - RABBITMQ_QUEUE_NAME=telegram
      - MSSQL_SERVER=172.22.0.3
      - MSSQL_PORT=1433
      - MSSQL_DATABASE=telegramdb
      - MSSQL_USERNAME=sa
      - MSSQL_PASSWORD=Pass*123
      - SERVER_PORT=52004
      - PRUNE_JOB_TIME=07:00 # 24 hr format of XX:XX i.e 05:00, 11:00, 18:30
    ports:
      - 52004:52004
    depends_on:
      - rabbitmq
    restart: on-failure
    volumes:
      - .:/telegram-sync:rw
      - ../logs:/logs
    networks:
      - ts_net